#!/usr/bin/env bash
# http://www.zalas.eu/viewing-svn-diff-result-in-colors
c=colordiff
if command -v $c >/dev/null 2>&1; then
	svn diff "${@}" | colordiff | less -R -F
else
	echo "install colordiff from http://www.colordiff.org/"
fi
